### ISSUE TITLE
styled-components injectGlobal

### ISSUE THREAD

**Issue by chvonrohr** [andrewnaeve/Full-Stack-Docker#1]
Using your boilerplate code, styled-components v4 is installed which removed `injectGlobal`

```
./src/app/utils/globalStyles.js
Attempted import error: 'injectGlobal' is not exported from 'styled-components'.
````
see: https://www.styled-components.com/docs/faqs#what-do-i-need-to-do-to-migrate-to-v4

fix: 
```jsx
import { createGlobalStyle } from 'styled-components';

const GlobalStyle = createGlobalStyle`
  ${reset}
  // ... styles
`;

export default GlobalStyle;
```

**Comment by andrewnaeve** [comment]
Looks like 3.3.3 was installed, but you're right- its time for an update. Fixed, thanks!
